env:
  global:
  - ENCRYPTION_LABEL: 9d3dcb13e73d  
  - COMMIT_AUTHOR_EMAIL: "comment@mynethome.de" 

before_script:
  - npm install
script: gulp
after_success: ./deploy.sh

# openssl aes-256-cbc -K $encrypted_9d3dcb13e73d_key -iv $encrypted_9d3dcb13e73d_iv -in id_rsa_hackergarten_deployment.enc -out ~\/.ssh/id_rsa_hackergarten_deployment -d

